name: Code quality
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ruff
        if: success() || failure()
        uses: jpetrucciani/ruff-check@main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
